# Basic
title: HeBao
subtitle: CQUST
description: 动态网站开发中
creator: <a href="http://hebaochina.top">@hebao123</a>

url: "http://hebaochina.top"

permalink: /:year/:month/:title/

# Format
highlighter: rouge

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: clear

# The blog button should not be removed.
blog_button:
    title: 美, description: 博客

# Navigation buttons in the front page.s
nav:
    - {title: 好, description: 检索, url: /tags}     
    - {title: 回, description: /tags}      
    - {title: 忆, description: archive}   
    
# Pagination
gems: [jekyll-paginate,jekyll-sitemap]
paginate: 10
paginate_path: "page/:num/"

# Comment
comment:
    # disqus: leopard
    duoshuo: hebao123 

# Social
social:
    weibo: 5252172579 
    wechat: http://mp.weixin.qq.com/profile?src=3&timestamp=1476096631&ver=1&signature=wNdazwX15sH*9OevwDjToRLRjUyHvwxB8nfXW2AOP21WvF4KwNKZsT-UH1Lqp3snwkrcELXmO0gTJQIsoz9q5A==
    
    mail: 879815165@qq.com

# 百度统计
baidu:
    id: 8ba1c6be0953b6f9c2ba38e57f615421  

# Google Analytics
ga:
    id: UA-84134159-3   
    host: auto  
