# Basic
title: 宝
subtitle: 庆 技 学院 
description: 
creator: <a href="http://hebaochina.top">@hebao123</a>

url: "http://hebaochina.top"

permalink: /:year/:month/:title/

# Format
highlighter: rouge

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: clear

# The blog button should not be removed.
blog_button:
    title: 博客

# Navigation buttons in the front page.s
nav:
    - {title: Team博客, description: Team博客}     
    - {title: 标签, description: tags}      
    - {title: 所有文章, description: archive}   
    
# Pagination
gems: [jekyll-paginate,jekyll-sitemap]
paginate: 10
paginate_path: "page/:num/"

# Comment
comment:
    # disqus: leopard
    duoshuo: hebao123 

# Social
social:
    weibo: 何宝美好回忆 
    github: hebao123
    # twitter: 
    mail: 879815165@qq.com

# 百度统计
baidu:
    id: 8ba1c6be0953b6f9c2ba38e57f615421  

# Google Analytics
ga:
    id: UA-84134159-3   
    host: auto  
