# Basic
title: 何宝
subtitle: 重庆科技学院
description: 动态网站开发中
creator: <a href="http://hebaochina.top">@hebao123</a>

url: "http://hebaochina.top"

permalink: /:year/:month/:title/

# Format
highlighter: rouge

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: clear

# The blog button should not be removed.
blog_button:
    {title: 美, description: 博客}

# Navigation buttons in the front page.s
nav:
    - {title: 好, description: 检索, url: /tags}     
    - {title: 回, description: /tags}      
    - {title: 忆, description: archive}   
    
# Pagination
gems: [jekyll-paginate,jekyll-sitemap]
paginate: 10
paginate_path: "page/:num/"

# Comment
comment:
    # disqus: leopard
    duoshuo: hebao123 

# Social
social:
    weibo: 5252172579 
    wechat: http://weixin.sogou.com/weixin?type=1&query=gh_d12e9f404e2c&ie=utf8&_sug_=n&_sug_type_=
    
    mail: 879815165@qq.com

# 百度统计
baidu:
    id: 76bd26bd1505edd9d6013fda8889ad58

# Google Analytics
ga:
    id:   
    host: auto  
